// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu11AhraTdA__rS85SDEiuP_l6IpvGDko',
    appId: '1:1000983055190:web:9d435520d66e9abe2764f7',
    messagingSenderId: '1000983055190',
    projectId: 'food-c0ebb',
    authDomain: 'food-c0ebb.firebaseapp.com',
    storageBucket: 'food-c0ebb.firebasestorage.app',
    measurementId: 'G-MLC17EMN8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDXGTQCBgpYZZ2Y1ufJN49RBA7i-qHB8',
    appId: '1:1000983055190:android:fd60665af1461ca82764f7',
    messagingSenderId: '1000983055190',
    projectId: 'food-c0ebb',
    storageBucket: 'food-c0ebb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu11AhraTdA__rS85SDEiuP_l6IpvGDko',
    appId: '1:1000983055190:web:0028355782f60ef22764f7',
    messagingSenderId: '1000983055190',
    projectId: 'food-c0ebb',
    authDomain: 'food-c0ebb.firebaseapp.com',
    storageBucket: 'food-c0ebb.firebasestorage.app',
    measurementId: 'G-D38GQ6GH8S',
  );
}
